"""
PR Creator - Creates Pull Requests with generated fixes
"""
from typing import Dict, List
from datetime import datetime


class PRCreator:
    """Creates Pull Requests for code fixes"""
    
    def __init__(self, llm):
        self.llm = llm
        
    async def create_pr(self, issue: Dict, fix: Dict, reasoning: List[Dict]) -> Dict:
        """Create a Pull Request with the fix"""
        
        # Generate PR metadata
        pr_title = self._generate_pr_title(issue)
        branch_name = self._generate_branch_name(issue)
        pr_description = self._generate_pr_description(issue, fix, reasoning)
        
        # In a real system, this would use GitHub API
        # For demo, we'll return PR metadata
        
        return {
            'title': pr_title,
            'branch': branch_name,
            'description': pr_description,
            'files': [self._get_file_from_issue(issue)],
            'labels': ['auto-generated', 'bug-fix', issue['severity'].lower()],
            'reviewers': ['tech-lead', 'senior-engineer'],
            'created_at': datetime.now().isoformat()
        }
    
    def _generate_pr_title(self, issue: Dict) -> str:
        """Generate PR title"""
        error_type = issue['error_type']
        location = issue['location'].split(':')[0] if ':' in issue['location'] else 'Unknown'
        
        return f"Fix {error_type} in {location}"
    
    def _generate_branch_name(self, issue: Dict) -> str:
        """Generate branch name"""
        error_type = issue['error_type'].lower().replace(' ', '-')
        timestamp = datetime.now().strftime('%Y%m%d')
        
        return f"auto-fix/{error_type}-{timestamp}"
    
    def _generate_pr_description(self, issue: Dict, fix: Dict, reasoning: List[Dict]) -> str:
        """Generate comprehensive PR description"""
        
        description = f"""## 🤖 Autonomous Fix Generated

### Issue Summary
- **Error Type**: {issue['error_type']}
- **Severity**: {issue['severity']}
- **Occurrences**: {issue['count']} times in last 24 hours
- **Location**: {issue['location']}

### Root Cause
{fix['explanation']}

### Solution
{fix['strategy']}

**Changes:**
- Lines modified: {fix['lines_changed']}
- Backward compatible: {'✅ Yes' if fix['backward_compatible'] else '❌ No'}
- Blast radius: LOW

### Agent Reasoning Process
"""
        
        for idx, step in enumerate(reasoning, 1):
            description += f"\n{idx}. **{step['action']}**\n"
            description += f"   - {step['description']}\n"
            if 'details' in step:
                for detail in step['details']:
                    description += f"   - {detail}\n"
        
        description += """
### Testing Recommendations
- [ ] Unit tests for null safety
- [ ] Integration tests with missing data scenarios
- [ ] Load test to verify performance impact

### Rollback Plan
If issues arise, revert this PR immediately. The previous behavior will be restored.

### Review Checklist
- [ ] Code follows team standards
- [ ] No security vulnerabilities introduced
- [ ] Performance impact is acceptable
- [ ] Documentation updated if needed

---
*This PR was automatically generated by the Autonomous Code Maintenance Agent*
*Confidence Score: 95%*
"""
        
        return description
    
    def _get_file_from_issue(self, issue: Dict) -> str:
        """Extract filename from issue location"""
        location = issue.get('location', 'Unknown')
        return location.split(':')[0] if ':' in location else location
